- name: Demo on cond
  hosts: all
  become: true
  vars:
    car: true
    bike: false
  tasks:
    - name: Printing  car names
      ansible.builtin.debug:
        msg: car name - DODGE
      when: car is true

    - name: Printing bike names
      ansible.builtin.debug:
        msg: bike name - HARLEY
      when: bike is true

    - name: installing nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
