- name: Demo on cond
  hosts: all
  become: true
  tasks:
    - name: Printing  car names
      ansible.builtin.debug:
        msg: car name is DODGE

    - name: Printing bike names
      ansible.builtin.debug:
        msg: Bike name is HARLEY